### ISSUE TITLE
Occasional failure in getblocktemplate_longpoll

### ISSUE THREAD

**Issue by ftrader** [BTCfork/hardfork_prototype_1_mvf-bu#48]
Occurred once during -only-extended qa run on 64-bit native Linux platform, could not be easily reproduced:

```
Running 2nd level testscript getblocktemplate_longpoll.py ...
Random seed: 1481632304
Initializing test directory /tmp/testneDMe1
Warning: this test will take about 70 seconds in the best case. Be patient.
Assertion failed: 
  File "/home/freetrader/mvf-bu/qa/rpc-tests/test_framework/test_framework.py", line 149, in main
    self.run_test()
  File "/home/freetrader/mvf-bu/qa/rpc-tests/getblocktemplate_longpoll.py", line 72, in run_test
    assert(not thr.is_alive())
Stopping nodes
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/freetrader/mvf-bu/qa/rpc-tests/getblocktemplate_longpoll.py", line 45, in run
    self.node.getblocktemplate({'longpollid':self.longpollid})
  File "/home/freetrader/mvf-bu/qa/rpc-tests/test_framework/coverage.py", line 44, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/home/freetrader/mvf-bu/qa/rpc-tests/test_framework/authproxy.py", line 138, in __call__
    response = self._request('POST', self.__url.path, postdata)
  File "/home/freetrader/mvf-bu/qa/rpc-tests/test_framework/authproxy.py", line 124, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/usr/lib/python2.7/httplib.py", line 1000, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1034, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 996, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 847, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 809, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 790, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
```

**Comment by ftrader** [comment]
Closing MVF prototype developments subsequent to release of Bitcoin Cash clients.
